// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmepjmpuykbperhmtpql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptZXBqbXB1eWticGVyaG10cHFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMzQ3MzksImV4cCI6MjA3MzkxMDczOX0.Nj2dhB--vb5ZHDEXttLo1lG8_Cle6Y2znOr4quLen04";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
