// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vealyprclkpagvcbwlcq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZlYWx5cHJjbGtwYWd2Y2J3bGNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1MTY5MjgsImV4cCI6MjA3NjA5MjkyOH0.MajE16rJ0btatajg2vP-SlMR04id73hR_sohOfg9mgo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
